version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/java_21"
    schedule:
      interval: "weekly"
    reviewers:
      - "stroeer/teams/buzz-end"
  - package-ecosystem: "docker"
    directory: "/java_22"
    schedule:
      interval: "weekly"
    reviewers:
      - "stroeer/teams/buzz-end"
