name: Publish Docker
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        repo: [ java_21 ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ghcr.io/stroeer/${{ matrix.repo }}

    steps:
    -
      uses: actions/checkout@master

    -
      name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
      id: extract_branch

    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    -
      name: dockerx build
      run: docker buildx build --platform linux/${{ matrix.arch }} --tag "${REPOSITORY}:${GITHUB_SHA}" ${{ matrix.repo }}/

    -
      name: docker push
      run: docker push --all-tags "${REPOSITORY}"