name: Publish Docker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  github:
    strategy:
      matrix:
        repo: [ java_21 ]

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    -
      uses: actions/checkout@master

    -
      name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
      id: extract_branch

    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    -
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.repo }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        provenance: false
        tags: |
          ghcr.io/stroeer/${{ matrix.repo }}:latest


  ecr:
    strategy:
      matrix:
        repo: [ custom-fluent-bit ]

    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      id-token: write
      contents: read

    steps:
    -
      uses: actions/checkout@master

    -
      name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
      id: extract_branch

    -
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@master
      if: ${{ github.event_name != 'pull_request' }}
      with:
        role-to-assume: arn:aws:iam::053041861227:role/github-ecr-access-eu-west-1
        role-session-name: GitHubActions
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      if: ${{ github.event_name != 'pull_request' }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.repo }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        provenance: false
        tags: |
          053041861227.dkr.ecr.eu-west-1.amazonaws.com/${{ matrix.repo }}:2.32.0-latest
          053041861227.dkr.ecr.eu-west-1.amazonaws.com/${{ matrix.repo }}:production

