name: Publish Docker
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        repo: [ java_21 ]

    runs-on: ubuntu-latest

    steps:
    -
      uses: actions/checkout@master

    -
      name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
      id: extract_branch

    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    -
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.repo }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/stroeer/java_21:${GITHUB_SHA}
